version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven dependencies
      - mvn install
  build:
    commands:
      - echo Running Unit Tests
      - mvn test

artifacts:
  files:
    - target/surefire-reports/*.xml
    - target/surefire-reports/*.txt
