version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies for testing
      - cd myapp
      - mvn install
  build:
    commands:
      - echo Running Unit Tests
      - cd myapp
      - mvn test

artifacts:
  files:
    - myapp/target/surefire-reports/*.xml
    - myapp/target/surefire-reports/*.txt
